name: Send Prayer Reminders

on:
  schedule:
    # Run daily at 10 AM UTC (good time to send reminders)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Prayer Reminders Edge Function
        run: |
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            'https://eqiafsygvfaifhoaewxi.supabase.co/functions/v1/send-prayer-reminders' \
            -H 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}' \
            -H 'Content-Type: application/json')
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          echo "Response: $BODY"
          
          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Error: Prayer reminders failed with status $HTTP_CODE"
            exit 1
          fi
          
          # Parse and display the number of reminders sent
          SENT=$(echo "$BODY" | grep -o '"sent":[0-9]*' | cut -d':' -f2)
          if [ -n "$SENT" ]; then
            echo "Successfully sent $SENT prayer reminder(s)"
          else
            echo "Prayer reminders completed"
          fi
          
      - name: Notify on Failure
        if: failure()
        run: |
          echo "::warning::Prayer reminders function failed. Check logs for details."
